### ISSUE TITLE
Reverse engineer Bettercare CSS into project SCSS

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/betterquiz#11]
When resources allow, we should reverse engineer this Bettercare-specific CSS into SASS, or simply integrate it somehow as a 'child theme'.

``` CSS
/* Styling for Bettercare to be reverse engineered into SASS */

/* Typography */
body {
  font-family: "Source Sans Pro", sans-serif;
  line-height: 140%;
  font-size: 1.3em;
}
input {
  font-size: 1em;
  font-family: inherit;
  letter-spacing: 0.025em;
  padding: 0.2em;
  margin: 0 0 1em 0;
  max-width: 90%;
}
input[type="radio"] {
    margin: 0;
}
input[type="submit"] {
  display: inline-block;
  background-color: #4f89d2;
  color: white;
  padding: 0.5em;
  margin: 0 0 1em 0;
  border-radius: 0.2em;
  text-align: center;
  text-decoration: none;
  line-height: 100%;
  box-shadow: 0.02em 0.02em 0.02em 0.02em #ccc;
  max-width: 100%;
  border: none;
  text-transform: capitalize;
}
    .yes, .no {
      display: inline-block;
      margin: 1em 1em 0 0;
    }
    .yes a, .no a, .question-navigate a {
      display: inline-block;
      background-color: #4f89d2; /* Bettercare blue */
      color: white;
      padding: 0.5em;
      margin: 0 0 1em 0;
      border-radius: 0.2em;
      text-align: center;
      text-decoration: none;
      line-height: 100%;
      box-shadow: 0.02em 0.02em 0.02em 0.02em #ccc;
      max-width: 100%;
    }
    .no a {
      background-color: #ff6644; /* Soft red */
    }
    .question-navigate a {
      background-color: grey;
    }
a {
  color: #4f89d2;
  text-decoration: none;
}

/* Navigation */
.link.exit, .link.profile {
  float: right;
  display: inline-block;
  margin: 0 1em 0 0;
  text-transform: capitalize;
}

/* Questions */
.question .question-text {
  font-size: inherit;
  clear: both;
  padding: 1em 0 0.5em 0;
}
.options {
  margin: 0 0 1em 0;
}
.question .options .option .option-text {
  display: inline;
}
.question-navigate {
  float: left;
  margin: 0 1em 0 0;
  text-transform: capitalize;
}
#register-form a {
  display: inline-block;
  margin: 0 1em 1em 0;
}
```
